# Generated by Django 5.1.7 on 2025-04-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
