# Generated by Django 5.1.7 on 2025-04-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0003_remove_photos_slug_album_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='created_at',
            new_name='date_uploaded',
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
