# Generated by Django 5.1.7 on 2025-04-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0004_rename_created_at_photos_date_uploaded_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='image',
            new_name='url',
        ),
    ]
