# Generated by Django 5.1.7 on 2025-04-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0005_rename_image_photos_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listalbum.album')),
            ],
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
