# Generated by Django 5.1.7 on 2025-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0006_photo_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
