# Generated by Django 5.1.7 on 2025-04-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0007_album_last_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='last_viewed',
        ),
    ]
