# Generated by Django 5.1.7 on 2025-04-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0008_remove_album_last_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
