# Generated by Django 5.1.7 on 2025-10-23 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0010_album_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='listalbum.album')),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='listalbum_a_email_786a04_idx')],
                'unique_together': {('album', 'email')},
            },
        ),
    ]
