# Generated by Django 5.1.7 on 2025-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0011_albumaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
