# Generated by Django 5.1.7 on 2025-12-09 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
