# Generated by Django 5.1.7 on 2025-12-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0014_album_uuid_photo_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payu_internal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
