# Generated by Django 5.1.7 on 2025-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0015_order_payu_internal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='full_album_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='photo_price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
