# Generated by Django 5.1.7 on 2025-12-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listalbum', '0016_album_full_album_price_album_photo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
